-- Run this in Supabase SQL Editor once.
create table if not exists public.joons_projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  project_id text not null,
  name text not null,
  folder_id text,
  payload_json jsonb not null,
  updated_at timestamptz not null default now()
);

create unique index if not exists joons_projects_user_project_uidx
  on public.joons_projects (user_id, project_id);

alter table public.joons_projects enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'joons_projects'
      and policyname = 'joons_projects_select_own'
  ) then
    create policy joons_projects_select_own
      on public.joons_projects
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'joons_projects'
      and policyname = 'joons_projects_insert_own'
  ) then
    create policy joons_projects_insert_own
      on public.joons_projects
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'joons_projects'
      and policyname = 'joons_projects_update_own'
  ) then
    create policy joons_projects_update_own
      on public.joons_projects
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'joons_projects'
      and policyname = 'joons_projects_delete_own'
  ) then
    create policy joons_projects_delete_own
      on public.joons_projects
      for delete
      using (auth.uid() = user_id);
  end if;
end $$;
